const imageBaseUrl = "https://bootx-chengyu.oss-cn-hangzhou.aliyuncs.com/chengyu"

const map:{[key:string]:string} = {
    "head_bg":"/static/images/account/head_bg.png",
    "redEnvelopeBg":"/static/images/account/redEnvelopeBg.png",
    "icon_home":"/static/images/answer/icon_home.png",
    "icon_prompt":"/static/images/answer/icon_prompt.png",
    "icon_share":"/static/images/answer/icon_share.png",
    "light":"/static/images/answer/light.png",
    "question_bg":"/static/images/answer/question_bg.png",
    "task1":"/static/images/answer/task1.png",
    "task2":"/static/images/answer/task2.png",
    "head":"/static/images/appList/head.png",
    "btn_increase":"/static/images/common/btn_increase.png",
    "btn_withdraw":"/static/images/common/btn_withdraw.png",
    "icon_msg":"/static/images/common/icon_msg.png",
    "icon_red_envelope":"/static/images/common/icon_red_envelope.png",
    "stamina":"/static/images/common/stamina.png",
    "tabbar_account":"/static/images/common/tabbar_account.png",
    "tabbar_account_active":"/static/images/common/tabbar_account_active.png",
    "tabbar_applist":"/static/images/common/tabbar_applist.png",
    "tabbar_applist_active":"/static/images/common/tabbar_applist_active.png",
    "tabbar_home_active":"/static/images/common/tabbar_home.active.png",
    "tabbar_home":"/static/images/common/tabbar_home.png",
    "tabbar_treasure":"/static/images/common/tabbar_treasure.png",
    "tabbar_treasure_active":"/static/images/common/tabbar_treasure_active.png",
    "redEnvelope_light":"/static/images/common/redEnvelope/light.png",
    "redEnvelope_bg":"/static/images/common/redEnvelope/bg.png",
    "redEnvelope_btn_hb":"/static/images/common/redEnvelope/btn_hb.png",
    "redEnvelope_close":"/static/images/common/redEnvelope/close.png",
    "redEnvelope_failure":"/static/images/common/redEnvelope/failure.png",
    "redEnvelope_icon_video":"/static/images/common/redEnvelope/icon_video.png",
    "redEnvelope_open":"/static/images/common/redEnvelope/open.png",
    "redEnvelope_open_share":"/static/images/common/redEnvelope/open_share.png",
    "redEnvelope_opened":"/static/images/common/redEnvelope/opened.png",
    "award_close":"/static/images/common/award/close.png",
    "award_bg":"/static/images/common/award/bg.png",
    "stamina_close":"/static/images/common/stamina/close.png",
    "stamina_icon":"/static/images/common/stamina/icon.png",
    "home_btn_start":"/static/images/home/btn_start.png",
    "home_fs":"/static/images/home/fs.png",
    "home_icon_invite":"/static/images/home/icon_invite.png",
    "home_icon_lottery":"/static/images/home/icon_lottery.png",
    "home_icon_ranking":"/static/images/home/icon_ranking.png",
    "home_icon_treasure":"/static/images/home/icon_treasure.png",
    "home_img_bz":"/static/images/home/img_bz.png",
    "home_img_100":"/static/images/home/img_100.png",
    "home_logo":"/static/images/home/logo.png",
    "home_logo_cywz":"/static/images/home/logo_cywz.png",
    "home_role":"/static/images/home/role.png",
    "home_role2":"/static/images/home/role2.png",
    "home_192_192":"/static/images/icon/192x192.png",
    "logo_role":"/static/images/logo/role.png",
    "logo_slogan":"/static/images/logo/slogan.png",
    "ranking_rank1":"/static/images/ranking/rank1.png",
    "ranking_rank2":"/static/images/ranking/rank2.png",
    "ranking_rank3":"/static/images/ranking/rank3.png",
    "ranking_title":"/static/images/ranking/title.png",
    "signin_close":"/static/images/signin/close.png",
    "signin_head_bg":"/static/images/signin/head_bg.png",
    "signin_icon_success":"/static/images/signin/icon_success.png",
}

export const imageUrl = (key:string) =>{
    return imageBaseUrl + map[`${key}`];
}